### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by StanfordLin**
Added navigation functionality

Added react-native-vector-icons, drawer-navigation

Test for: logout button, should route when buttons are tapped, authentication before being able to navigate 

Honestly running the simulator using react native scares me, it eats so much ram LOL

IOS:

Simulator Screen Shot - iPhone 11 - 2019-12-25 at 03 14 07 Simulator Screen Shot - iPhone 11 - 2019-12-25 at 03 14 03
Simulator Screen Shot - iPhone 11 - 2019-12-25 at 03 14 12
Simulator Screen Shot - iPhone 11 - 2019-12-25 at 03 20 18

Android:
Screenshot_20191225-040619

### CODE REVIEW

**Comment by Ciuffi** [comment]
The drawer looks great. Just one little issues with the burger button. Not sure if this is intentional but it seems like its a bit low on my phone.
IMG_0014

**Comment by StanfordLin** [comment]
> reat. Just one little issues with the burger button. Not sure if this is intentional but it seems like its a bit low on my phone.

Yes, it's to accomodate for the notch on the iphone x and onwards, I tried to load it onto my iphone but having signing issues b/c of NFC

**Comment by Ciuffi** [comment]
it’s strange that the simulator looks like that because on my phone I don’t have the time in the top left.. 

i’ll do some testing because they should be exactly the same

**Comment by StanfordLin** [comment]
> it’s strange that the simulator looks like that because on my phone I don’t have the time in the top left..
> 
> i’ll do some testing because they should be exactly the same

I tested on android and the drawer icon was a bit low as well, but after changing, it sits up in the notch of the simulator. The only value that needed to be changed was line 19 on MenuButton.js to 10 in the components folder, so maybe try that on the physical device? If it works I'll just push the change

Screen Shot 2019-12-26 at 1 00 32 AM

**Comment by Ciuffi** [comment]
@StanfordLin I tried changing the value earlier and it worked. I’m just worried it might mess up the view on smaller phones

**Comment by StanfordLin** [comment]
> @StanfordLin I tried changing the value earlier and it worked. I’m just worried it might mess up the view on smaller phones

I tested on iphone 8 on simulator and the pixel xl, and they both seem to be ok, I think the smallest device we'll probably see is iphone 6s... even if it's a smaller device, they can still slide from the left edge of the screen to the right to see the drawer so I think it should be ok :p

**Pull request merged**
